<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="ironman_theme.mp3" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="ironman_theme.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.3.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="System.Speech" Version="10.0.8" />
		<PackageReference Include="Vosk" Version="0.3.38" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="model\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\espeak-ng.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\onnxruntime.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\onnxruntime_providers_shared.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\piper.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\piper_phonemize.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\uk_UA-mykyta-high.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="piper\uk_UA-mykyta-high.onnx.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Content Include="piper\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
